baseURL = "https://kinghh.cn/"
title = "首页"
theme = "blowfish"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
summaryLength = 120
enableEmoji = true

[pagination]
  pagerSize = 20

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
