server {
    listen 80;
    server_name kinghh.cn www.kinghh.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kinghh.cn www.kinghh.cn;

    root /opt/blog/frontend/dist;
    index index.html;

    access_log /var/log/nginx/kinghh-blog-app.access.log;
    error_log /var/log/nginx/kinghh-blog-app.error.log;

    include snippets/jenkins-proxy.conf;
    include snippets/kinghh-stats.conf;
    include snippets/kinghh-waline.conf;

    ssl_certificate /etc/letsencrypt/live/kinghh.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kinghh.cn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location ^~ /api/ {
        proxy_pass http://127.0.0.1:18080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }
}
